version: '3.8'

services:
  redis-1:
    image: redis:latest
    restart: always
    command: redis-server --port 6379 --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data-1:/data

  redis-2:
    image: redis:latest
    restart: always
    command: redis-server --port 6380 --save 20 1 --loglevel warning
    ports:
      - 6380:6380
    volumes:
      - redis-data-2:/data

  redis-3:
    image: redis:latest
    restart: always
    command: redis-server --port 6381 --save 20 1 --loglevel warning
    ports:
      - 6381:6381
    volumes:
      - redis-data-3:/data

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:
