services:
  redis-1:
    image: redis:latest
    restart: always
    command: redis-server --port 6379 --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - redis-data-1:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 1s
      timeout: 5s
      retries: 5

  redis-2:
    image: redis:latest
    restart: always
    command: redis-server --port 6380 --save 20 1 --loglevel warning
    ports:
      - 6380:6380
    volumes:
      - redis-data-2:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6380", "ping"]
      interval: 1s
      timeout: 5s
      retries: 5

  redis-3:
    image: redis:latest
    restart: always
    command: redis-server --port 6381 --save 20 1 --loglevel warning
    ports:
      - 6381:6381
    volumes:
      - redis-data-3:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6381", "ping"]
      interval: 1s
      timeout: 5s
      retries: 5
  
  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis-1
      - redis-2
      - redis-3

volumes:
  redis-data-1:
  redis-data-2:
  redis-data-3:

networks:
  default:
    driver: host